export const GET_ALL_CHARACTERS = 'GET_ALL_CHARACTERS';
export const GET_ALL_DETAILS = 'GET_ALL_DETAILS';
export const SET_DETAIL_CHARACTER = 'SET_DETAIL_CHARACTER';
export const GET_ALL_PLANETS = 'GET_ALL_PLANETS';
export const GET_PLANETS_DETAIL = 'GET_PLANETS_DETAIL';
export const SET_PLANETS_DETAIL = 'SET_PLANETS_DETAIL';